### ISSUE TITLE
Code Understanding

### ISSUE THREAD

**Issue by as900** [ZacharyPage/Study-Session#1]
Hi there, When I was learning and trying to understand the function "merge_cookies" in Study-Session/venv/Lib/site-packages/pip-10.0.1-py3.7.egg/pip/_vendor/requests/cookies.py, I was confused about the description of its delivered function. My understanding of this code snippet is "add cookies to cookiejar and returns a merged cookiejar". Do I understand that right?

**Comment by ZacharyPage** [comment]
That code snippet at the end essentially just merges cookies, correct. Whilst the whole code manages cookie policies.
